<?php

return [
    'Aer Conditionat' => 'aer-conditionat.svg',
    'Artificii Exterior' => 'artificii-exterior.svg',
    'Autorizatie DSP' => 'autorizatie-dsp.svg',
    'Autorizatie ISU' => 'autorizatie-isu.svg',
    'Bucatarie Proprie' => 'bucatarie-proprie.svg',
    'Accepta Catering' => 'accepta-catering.svg',
    'Ofera Catering' => 'oferta-catering.svg',
    'Cazare Invitati' => 'cazare-invitati.svg',
    'Cazare Miri' => 'cazare-miri.svg',
    'Loc Cununie' => 'loc-cununie.svg',
    'Curent 380 V' => 'curent-380v.svg',
    'Fara Taxe Suplimentare' => 'fara-taxe-suplimentare.svg',
    'Garderoba' => 'wardrobe.svg',
    'Generator' => 'generator-curent.svg',
    'Gradina' => 'gradina.svg',
    'Hostess' => 'hostess.svg',
    'Lac' => 'lac.svg',
    'Loc De Fumat' => 'zona-fumat.svg',
    'Loc De Joaca' => 'loc-de-joaca.svg',
    'Loc Photo Corner' => 'loc-photo-corner.svg',
    'Padure' => 'padure.svg',
    'Parcare Proprie' => 'parcare-proprie.svg',
    'Permite bautura din afara locatiei' => 'permite-bauturi-din-afara-locatiei.svg',
    'Piscina' => 'piscina.svg',
    'Plata Card' => 'plata-card.svg',
    'Plata Cash' => 'plata-cash.svg',
    'Posibilitate Barbeque' => 'available-barbeque.svg',
    'Ring De Dans Dedicat' => 'ring-de-dans-dedicat.svg',
    'Sistem Audio' => 'sistem-audio.svg',
    'Taxi/Ridesharing' => 'taxi-ridesharing.svg',
    'Transport Invitati' => 'transport-la-locatie.svg',
    'Wireless' => 'wireless.svg',
    'Zona Cocktail' => 'zona-cocktail.svg',
    'Aranjamente Mese Standard' => 'aranjamente-mese-standard.svg',
    'Ring De Dans' => 'ring-de-dans.svg',
    'Spatiu Acoperit' => 'spatiu-acoperit.svg',
    'Terasa' => 'terasa.svg',
    'Ballroom' => 'ballroom.svg',
    'Candy Bar' => 'candy-bar.svg',
    'Live Cooking' => 'live-cooking.svg',
    'Serviciu BBQ' => 'serviciu-bbq.svg',
    'Protap' => 'protap.svg',
    'Livrare Mancare' => 'livrare-mancare.svg',
    'Outdoor wedding option' => 'outdoor-wedding-option.svg',
];

